version: "3.9"
services:
  etcd:
    image: "gcr.io/etcd-development/etcd:latest"
    hostname: "etcd0"
    ports:
      - 2379:2379
      - 2380:2380
    command: [
      "etcd",
      "--name=etcd0",
      "--data-dir=/etcd-data",
      "--initial-advertise-peer-urls=http://etcd0:2380",
      "--listen-peer-urls=http://0.0.0.0:2380",
      "--advertise-client-urls=http://etcd0:2379",
      "--listen-client-urls=http://0.0.0.0:2379",
      "--initial-cluster=etcd0",
    ]
  grpc-proxy:
    depends_on:
      - "etcd"
    image: "gcr.io/etcd-development/etcd:latest"
    command: [
      "etcd",
      "grpc-proxy",
      "start",
      "--endpoints=etcd0",
      "--listen-addr=127.0.0.1",
    ]
    ports:
      - 2379:2379
      - 4001:4001
  app:
    depends_on:
      - grpc-proxy
    build: .
    hostname: app
    restart: always
