version: "3.9"
services:
  etcd:
    image: "gcr.io/etcd-development/etcd:latest"
    hostname: "etcd0"
    ports:
      - 2379:2379
      - 2380:2380
    command: [
      "etcd",
      "--name=node0",
      "--data-dir=/etcd-data",
      "--initial-advertise-peer-urls=http://etcd0:2380",
      "--listen-peer-urls=http://0.0.0.0:2380",
      "--advertise-client-urls=http://etcd0:2379",
      "--listen-client-urls=http://0.0.0.0:2379",
      "--initial-cluster=node0=http://etcd0:2380",
    ]
  grpc-proxy:
    hostname: "grpc-proxy"
    depends_on:
      - "etcd"
    image: "gcr.io/etcd-development/etcd:latest"
    command: [
      "etcd",
      "grpc-proxy",
      "start",
      "--endpoints=etcd0:2379",
      "--listen-addr=127.0.0.1:2381",
      "--advertise-client-url=127.0.0.1:2381",
    ]
    ports:
      - 2381:2381
      - 4001:4001
